name: Website CI Build PR

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build project
        env:
          GATSBY_DATACORE_URL: https://datacore.app/
          GATSBY_ASSETS_URL: https://assets.datacore.app/
        run: |
          npm install
          npm run build
